### ISSUE TITLE
atlas fails to install

### ISSUE THREAD

**Issue by joshwalawender** [camphogg/homebrew-science#6]
I attempted to install atlas with the following result:

```
==> Installing atlas
==> Downloading http://sourceforge.net/projects/math-atlas/files/Stable/3.10.0/atlas3.10.0.tar.bz2
######################################################################## 100.0%
==> mkdir -p BUILD
==> curl -C - -o lapack-3.4.2.tgz http://www.netlib.org/lapack/lapack-3.4.2.tgz
==> ../configure --nof77 --with-netlib-lapack-tarfile=/private/tmp/atlas-gPiI8Z/ATLAS/BUILD/lapack-3.4.2.tgz --prefix=/usr/local/Cellar/atlas/3.10.0 --dylibs
==> make build


BEGIN STAGE 1-0-0: SYSTEM PROBE/AUX COMPILE at 16:52
make[1]: *** [build] Error 255
make: *** [build] Error 2

READ THIS: http://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/camphogg/homebrew-science/issues
```

Here's the [gist](https://gist.github.com/51cfa04aa0b2c21a54a6)

**Comment by mwcraig** [comment]
@joshwalawender -- are you trying to install ATLAS because you need it for `SExtractor`?

**Comment by joshwalawender** [comment]
Close.  I need it for SCAMP.

**Comment by mwcraig** [comment]
Ah...no immediate fix for that. I patched up sextractor a few months ago to brew without ATLAS, can take a look at something similar for SCAMP tomorrow. Gave up on getting ATLAS to compile about a year ago.

**Comment by mwcraig** [comment]
@joshwalawender -- I have a SCAMP that compiles without ATLAS now...no idea if it *works correctly* since I've never used it. If I work it up into a brew formula can you try installing it and testing?

**Comment by joshwalawender** [comment]
Sure, I'd be happy to try it out.

**Comment by mwcraig** [comment]
Give this a try, @joshwalawender; first one is optional, had to modify the formula for plplot to make scamp work (if both build/work fine for you then I'll do a PR in the appropriate repos for each, am aware of the thread in brew about the plplot formula).

```
brew install https://raw.githubusercontent.com/mwcraig/homebrew/fix-plplot-36569/Library/Formula/plplot.rb

brew install https://raw.githubusercontent.com/mwcraig/camphogg-homebrew-science/scamp/scamp.rb
```

**Comment by joshwalawender** [comment]
Hi @mwcraig, the brew install seemed to work fine.  I had some trouble as there was remnants of an old scamp install, so I had to chown /usr/local/share/scamp, but one I did that, the subsequent linking worked.

The problem is, I now get a segfault when I use scamp:
```
[trapezium] ~/IQMon/tmp/VYSOS-5 > scamp test.cat

> WARNING: scamp.conf not found, using internal defaults

----- SCAMP 2.0.4 started on 2015-03-03 at 15:21:22 with 8 threads

----- 1 inputs:
> Examining Catalog test.cat
Segmentation fault
```

I had a similar problem on another computer (I think the dependancies on that computer were installed with macports).  Not sure if it is relevant, but you can see the thread here:
http://www.astromatic.net/forum/showthread.php?tid=956

thanks,
Josh

**Comment by mwcraig** [comment]
@joshwalawender -- I sent you an email asking for some more details since we are getting pretty far astray from ATLAS :)

**Comment by mwcraig** [comment]
@joshwalawender -- fixed (I think) version is installable with:

```
https://raw.githubusercontent.com/mwcraig/camphogg-homebrew-science/scamp/scamp.rb
```
You may need to ``brew uninstall scamp`` first.

**Comment by joshwalawender** [comment]
That looks to have solved it for me.  Thanks!
