### ISSUE TITLE
Formula.sha1 disabled

### ISSUE THREAD

**Issue by anumore** [camphogg/homebrew-science#9]
@davidwhogg 
I got the following error during  brew upgrade. could you please check? thanks!

Updating Homebrew...
Error: Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/camphogg/homebrew-science/sextractor.rb:6:in `<class:Sextractor>'
Please report this to the camphogg/science tap!

**Comment by dstndstn** [comment]
Hi,

The camphogg/homebrew-science tap is very much out of date.  The astrometry-net package is now in the main homebrew/homebrew-science tap, so the camphogg tap is no longer necessary.  Could you please:

```
brew untap camphogg/science
brew tap homebrew/science
```

Thanks!
--dustin

**Comment by anumore** [comment]
@dstndstn  Thanks for the info.
